### ISSUE TITLE
Invalid yaml config upgrading from 0.4.0 to 0.4.1

### ISSUE THREAD

**Issue by parautenbach** [kucherenko/jscpd#37]
This config used to work fine with v0.4.0 until v0.4.1 was released just now:

```yaml
path:
  - .
languages:
  - javascript
  - coffeescript
exclude:
  - "node_modules/**"
  - "test/**"
  - "public/lib/**"
output: "cpd.xml"
```

```
File .../src/.cpd.yml not found in current directory, or it is broken
```
